server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 # 컬렉션들의 레이지 로딩 발생 시 컬렉션 중 하나의 프록시에서 lazy 로딩이 호출되도 모든 컬렉션을 in 쿼리로 한번에 조회
#    open-in-view: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        messaging:
          simp:
            user: TRACE
        security: DEBUG

file:
  path: C:\temp